### ISSUE TITLE
Errors on kscript invocation

### ISSUE THREAD

**Issue by rewireWI** [holgerbrandl/kscript#120]
Very first try of kscript with: 

kscript -t 'lines.split().select(10,1,12).print()' some_flights.tsv

results in:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at Main_Scriptlet_cf6c40ff899dcf3d$Companion.main(Main_Scriptlet_cf6c40ff899dcf3d.kt:6)
        at Main_Scriptlet_cf6c40ff899dcf3d.main(Main_Scriptlet_cf6c40ff899dcf3d.kt)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
Caused by: java.lang.IndexOutOfBoundsException: Index: 9, Size: 3
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at kscript.text.Row.get(Tables.kt:32)
        at kscript.text.PosSelect$process$1.invoke(Tables.kt:103)
        at kscript.text.PosSelect$process$1.invoke(Tables.kt:99)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:148)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:148)
        at kscript.text.StreamUtilKt.print(StreamUtil.kt:76)
        at kscript.text.TablesKt.print(Tables.kt:73)
        at kscript.text.TablesKt.print$default(Tables.kt:73)
        at Scriptlet_cf6c40ff899dcf3d.<init>(Unknown Source)
        ... 13 more

**Comment by hj-lee** [comment]
> Caused by: java.lang.IndexOutOfBoundsException: Index: 9, Size: 3

It happened because the tsv file doesn't have enough columns.

**Comment by holgerbrandl** [comment]
Indeed. But doesn't this make it a problem of your input data/processing logic? To me, it does not seem to be a problem with kscript itself. What do you think?

**Comment by hj-lee** [comment]
@holgerbrandl 
I don't think this issue is a problem of kscript, either. (I'm not the issuer of this issue. I looked at this issue and experimented a little bit as it is labeled as "help wanted".)

**Comment by holgerbrandl** [comment]
Oh that's "how help" wanted is supposed to be used. I typically assigned it to tickets which seem more to be user support than an actual issue. I'll use a different tag.

**Comment by holgerbrandl** [comment]
Closed due to inactivity. Feel welcome to reopen if needed!
