### ISSUE TITLE
kscript fails to generate function in certain conditions

### ISSUE THREAD

**Issue by seanabraham** [holgerbrandl/kscript#124]
Here's a simple repro (which I believe is valid Kotlin, correct me if I'm wrong):

With a file called `kscript_broken_test.kts`:
```
fun String.test(): String {
  return this
}

object Foo {
  fun bar() {
    "hi".test()
  }
}
```
Running `kscript kscript_broken_test.kts` yields the following:
```
[kscript] [ERROR] compilation of 'kscript_broken_test.kts' failed
kscript_broken_test.kts:6:3: exception: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Failed to generate function bar
Cause: Don't know how to generate outer expression: Class: class Foo
File being compiled at position: (6,3) in /path/to/kscript_broken_test.kts
The root cause was thrown at: CodegenContext.java:215
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:205)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateDeclaration(ClassBodyCodegen.java:161)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateBody(ClassBodyCodegen.java:75)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:131)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:305)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:289)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:315)
	at org.jetbrains.kotlin.codegen.ScriptCodegen.genMembers(ScriptCodegen.kt:166)
	at org.jetbrains.kotlin.codegen.ScriptCodegen.generateBody(ScriptCodegen.kt:49)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:131)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:115)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:97)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:68)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:47)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:39)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:454)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyzeAndGenerate(KotlinToJVMBytecodeCompiler.kt:356)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileBunchOfSources(KotlinToJVMBytecodeCompiler.kt:245)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:207)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:63)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:96)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:72)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:38)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:171)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:162)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler$Companion.main(K2JVMCompiler.kt:329)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.main(K2JVMCompiler.kt)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.kotlin.preloading.Preloader.run(Preloader.java:81)
	at org.jetbrains.kotlin.preloading.Preloader.main(Preloader.java:43)
Caused by: java.lang.UnsupportedOperationException: Don't know how to generate outer expression: Class: class Foo
	at org.jetbrains.kotlin.codegen.context.CodegenContext.getOuterExpression(CodegenContext.java:215)
	at org.jetbrains.kotlin.codegen.context.CodegenContext.getOuterExpression(CodegenContext.java:209)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.generateScriptReceiver(ExpressionCodegen.java:2668)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.generateReceiverValue(ExpressionCodegen.java:2604)
	at org.jetbrains.kotlin.codegen.StackValue.genReceiver(StackValue.java:704)
	at org.jetbrains.kotlin.codegen.StackValue.receiver(StackValue.java:680)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putReceiverAndInlineMarkerIfNeeded(ExpressionCodegen.java:2429)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2360)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2347)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:41)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:13)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:79)
	at org.jetbrains.kotlin.codegen.StackValueWithLeaveTask.putSelector(StackValue.kt:67)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:109)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:98)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putStackValue(ExpressionCodegen.java:349)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:334)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.returnExpression(ExpressionCodegen.java:1621)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$FunctionDefault.doGenerateBody(FunctionGenerationStrategy.java:60)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:80)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:620)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:391)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:244)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:168)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.gen(FunctionCodegen.java:139)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:199)
	... 35 more

  fun bar() {
  ^
```

If I use the extension function outside the object, or call a different function (not an extension function) on the string in `bar()`, everything works fine.

Any thoughts?

**Comment by seanabraham** [comment]
Looking more closely, it's probably not a kscript issue as `kotlinc -script kscript_broken_test.kts` also chokes on this with the same exception (which makes sense since the error comes from the compiler itself)

**Comment by holgerbrandl** [comment]
Indeed its a compiler problem. Did you find/file a youtrack ticket for it already which I could upvote?

**Comment by seanabraham** [comment]
@holgerbrandl here's the youtrack ticket: https://youtrack.jetbrains.com/issue/KT-24457

**Comment by holgerbrandl** [comment]
Thanks for reporting it. Let's see what they say. :-)
