### ISSUE TITLE
kscript isn't able to find kafka StringSerializer class

### ISSUE THREAD

**Issue by hshar7** [holgerbrandl/kscript#131]
Hi i have the following simple script:
```
#!/usr/bin/env kscript
 @file:DependsOn("org.apache.kafka:kafka-clients:1.1.0")

 import java.util.Properties
 import org.apache.kafka.clients.producer.KafkaProducer
 import org.apache.kafka.clients.producer.ProducerRecord
 import org.apache.kafka.common.serialization.StringSerializer

 val properties = Properties()
 properties.setProperty("bootstrap.servers", "localhost:9092")
 properties.setProperty("topic", "topic1")
 properties.setProperty("acks", "all")
 properties.setProperty("retries", "0")
 properties.setProperty("batch.size", "16384")
 properties.setProperty("linger.ms", "1")
 properties.setProperty("buffer.memory", "33554432")
 properties.setProperty("key.serializer", "org.apache.kafka.common.serialization.StringSerializer")
 properties.setProperty("value.serializer", "org.apache.kafka.common.serialization.StringSerializer")
 val producer = KafkaProducer<String, String>(properties)

 producer.send(ProducerRecord(properties.getProperty("topic"), "exampleKey", "exampleValue"))
 producer.close()
```
I am receiving the following error when running it:
```
[kscript] Resolving dependencies...Done
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at Main_Script2$Companion.main(Main_Script2.kt:6)
	at Main_Script2.main(Main_Script2.kt)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.serialization.StringSerializer for configuration key.serializer: Class org.apache.kafka.common.serialization.StringSerializer could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:724)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:469)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:462)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
	at org.apache.kafka.clients.producer.ProducerConfig.<init>(ProducerConfig.java:365)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303)
	at Script2.<init>(Unknown Source)
	... 13 more
```

Not really sure why it isn't able to see that class.

Any ideas?

**Comment by holgerbrandl** [comment]
Same here.

However, I don't think that this is a `kscript` problem. It's rather a Kotlin issue. See https://youtrack.jetbrains.net/issue/KT-24966

**Comment by hshar7** [comment]
Thanks for following up with that! Doesn't seem to be any workaround for now.

**Comment by holgerbrandl** [comment]
As pointed out in the kotlin-ticket, a workaround around the class-loader issue would be to 
```
props.put("key.serializer", Class.forName("org.apache.kafka.common.serialization.StringSerializer"));
props.put("value.serializer", Class.forName("org.apache.kafka.common.serialization.StringSerializer"));
```
