### ISSUE TITLE
Improve usability in environment less launches

### ISSUE THREAD

**Issue by Prototik** [holgerbrandl/kscript#145]
First of all kscript [requires `HOME` env variable](https://github.com/holgerbrandl/kscript/blob/d20473d580d3de29d2788d4ce80a764627a9372b/src/main/kotlin/kscript/app/Kscript.kt#L54) to launch:
```
$ kscript hello.kts
Hello!
$ unset HOME
$ kscript hello.kts
Exception in thread "main" java.lang.ExceptionInInitializerError
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
Caused by: kotlin.KotlinNullPointerException
	at kscript.app.KscriptKt.<clinit>(Kscript.kt:54)
	... 7 more
```

Second, kscript requires `kotlin` in PATH, I suggest to add some property (`--kotlin-home` or something else) to point kotlin executable to use.

**Comment by holgerbrandl** [comment]
Indeed it infers your home via HOME. Is there a more setup agnostic way to detect a directory in which we could deposit the cache files?

It check for KOTLIN_HOME but just to find `kotlinc` and not for execution. I'll have a look asap.

**Comment by Prototik** [comment]
`System.getProperty("user.dir")` could be the way. If no any path can be discovered probably the best way just to save it to tmp (via `java.io.tmpdir` property or `File.createTempFile`)

**Comment by holgerbrandl** [comment]
The most common solution seems to be `user.home` https://stackoverflow.com/questions/585534/what-is-the-best-way-to-find-the-users-home-directory-in-java

I  don't really like tmp-dir, because `kscript` cached files are meant to be speed up execution and dependency lookup, and are thus not really temporary.

**Comment by Prototik** [comment]
Yeah, right, `user.home`. `user.dir` refers directory where `java` was launched (cwd).
