### ISSUE TITLE
Type Errors when using .kts files with runBlocking and a DSL

### ISSUE THREAD

**Issue by NikkyAI** [holgerbrandl/kscript#161]
i am not entirely sure if this is the most simple example, i hope it is

this also breaks when the DSL functions come from a library and are just imported

replacing runBlocking with just `run` or `apply`  simplifies the error a lot

**ALL** these cases work fine once wrapped in a `main` function and **only** error in a .kts
```kotlin
@file:DependsOnMaven("org.jetbrains.kotlinx:kotlinx-coroutines-core:0.25.3")

import kotlinx.coroutines.experimental.CoroutineExceptionHandler
import kotlinx.coroutines.experimental.runBlocking

@DslMarker
annotation class DSL

data class Entry(
        var name: String,
        var entries: List<Entry> = listOf()
) {
    fun flatten(): List<String> {
        val result = mutableListOf(name)
        result += entries.flatMap { it.flatten() }
        return result
    }
}

@DSL
class EntryEnv(val entry: Entry)

@DSL
class ListEnv {
    val entriess: MutableList<EntryEnv> = mutableListOf<EntryEnv>()
}

fun root(name: String, function: EntryEnv.() -> Unit): Entry {
    val entry = Entry(name)
    val env = EntryEnv(entry)
    env.function()
    return entry
}

fun ListEnv.entry(name: String, function: EntryEnv.() -> Unit = {}): EntryEnv {
    val entry = Entry(name)
    val env = EntryEnv(entry)
    env.function()
    return env.also { this.entriess += it }
}

fun EntryEnv.entries(function: ListEnv.() -> Unit) {
    ListEnv().apply {
        function()
        this@entries.entry.entries += this.entriess.map { it.entry }
    }
}

val exceptionHandler = CoroutineExceptionHandler { _, exception ->
    exception.printStackTrace()
    println(exception.message)
}

//fun main(args: Array<String>) {
val entry = root("root") {
    entries {
        entry("something")
        entry("is")
        entry("subentry").entries {
            entry("broken")
        }
    }
}

// name matches the function, change this to fix it,

val entries = runBlocking {
    entry.flatten()
}
println(entries)

// this runs into a recursive typechacking error
val entries = entry.flatten()
println(entries)

val entriesList = runBlocking {
    entry.flatten()
}
println(entriesList)
```

`
val entries = runBlocking {
    entry.flatten()
}
` causes error

```
[kscript] [ERROR] compilation of 'test.kts' failed
exception: java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: Back-end (JVM) Internal error: Failed to generate property entries
Cause: Error type encountered: [ERROR : Type for runBlocking {
    entry.flatten()
}] (DeferredType).
File being compiled at position: (67,1) in /home/nikky/dev/VoodooDSLTest/test.kts
The root cause was thrown at: KotlinTypeMapper.java:113
File being compiled at position: file:///home/nikky/dev/VoodooDSLTest/test.kts
The root cause was thrown at: MemberCodegen.java:218
        at org.jetbrains.kotlin.codegen.CompilationErrorHandler.lambda$static$0(CompilationErrorHandler.java:24)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:74)
        at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:97)
        at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:68)
        at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:47)
        at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:39)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:441)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyzeAndGenerate(KotlinToJVMBytecodeCompiler.kt:349)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileBunchOfSources(KotlinToJVMBytecodeCompiler.kt:242)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:200)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:94)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:50)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:88)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:66)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:34)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:180)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:171)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler$Companion.main(K2JVMCompiler.kt:341)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.main(K2JVMCompiler.kt)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.preloading.Preloader.run(Preloader.java:81)
        at org.jetbrains.kotlin.preloading.Preloader.main(Preloader.java:43)
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Failed to generate property entries
Cause: Error type encountered: [ERROR : Type for runBlocking {
    entry.flatten()
}] (DeferredType).
File being compiled at position: (67,1) in /home/nikky/dev/VoodooDSLTest/test.kts
The root cause was thrown at: KotlinTypeMapper.java:113
        at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:218)
        at org.jetbrains.kotlin.codegen.ScriptCodegen.genMembers(ScriptCodegen.kt:224)
        at org.jetbrains.kotlin.codegen.ScriptCodegen.generateBody(ScriptCodegen.kt:51)
        at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:133)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:115)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
        ... 24 more
Caused by: java.lang.IllegalStateException: Error type encountered: [ERROR : Type for runBlocking {
    entry.flatten()
}] (DeferredType).
        at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$1.processErrorType(KotlinTypeMapper.java:113)
        at org.jetbrains.kotlin.load.kotlin.TypeSignatureMappingKt.mapType(typeSignatureMapping.kt:92)
        at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.java:502)
        at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.java:458)
        at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.java:469)
        at org.jetbrains.kotlin.codegen.PropertyCodegen.shouldWriteFieldInitializer(PropertyCodegen.java:486)
        at org.jetbrains.kotlin.codegen.PropertyCodegen.generateBackingFieldAccess(PropertyCodegen.java:473)
        at org.jetbrains.kotlin.codegen.PropertyCodegen.generateBackingField(PropertyCodegen.java:342)
        at org.jetbrains.kotlin.codegen.PropertyCodegen.genBackingFieldAndAnnotations(PropertyCodegen.java:187)
        at org.jetbrains.kotlin.codegen.PropertyCodegen.gen(PropertyCodegen.java:134)
        at org.jetbrains.kotlin.codegen.PropertyCodegen.gen(PropertyCodegen.java:104)
        at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:212)
        ... 29 more
```

`val entries = entry.flatten()` causes error
```
[kscript] [ERROR] compilation of 'test.kts' failed
test.kts:73:15: error: type checking has run into a recursive problem. Easiest workaround: specify types of your declarations explicitly
val entries = entry.flatten()
              ^
```

`val entries = run {
    entry.flatten()
}` causes 
```
[kscript] [ERROR] compilation of 'test.kts' failed
teste.kts:68:5: error: type checking has run into a recursive problem. Easiest workaround: specify types of your declarations explicitly
    entry.flatten()
    ^
```

**Comment by holgerbrandl** [comment]
Imho this is either a platform or a coroutines bug. Noteably, it is also not a scripting problem, since my revised example is a regular kotlin application. Consider the following program (which does not rely on kscript in any way:

```
@file:DependsOnMaven("org.jetbrains.kotlinx:kotlinx-coroutines-core:0.25.3")

package kscript

import DependsOnMaven
import kotlinx.coroutines.experimental.CoroutineExceptionHandler
import kotlinx.coroutines.experimental.runBlocking

@DslMarker
annotation class DSL

data class Entry(
    var name: String,
    var entries: List<Entry> = listOf()
) {
    fun flatten(): List<String> {
        val result = mutableListOf(name)
        result += entries.flatMap { it.flatten() }
        return result
    }
}

@DSL
class EntryEnv(val entry: Entry)

@DSL
class ListEnv {
    val entriess: MutableList<EntryEnv> = mutableListOf<EntryEnv>()
}

fun root(name: String, function: EntryEnv.() -> Unit): Entry {
    val entry = Entry(name)
    val env = EntryEnv(entry)
    env.function()
    return entry
}

fun ListEnv.entry(name: String, function: EntryEnv.() -> Unit = {}): EntryEnv {
    val entry = Entry(name)
    val env = EntryEnv(entry)
    env.function()
    return env.also { this.entriess += it }
}

fun EntryEnv.entries(function: ListEnv.() -> Unit) {
    ListEnv().apply {
        function()
        this@entries.entry.entries += this.entriess.map { it.entry }
    }
}

val exceptionHandler = CoroutineExceptionHandler { _, exception ->
    exception.printStackTrace()
    println(exception.message)
}

val entry = root("root") {
    entries {
        entry("something")
        entry("is")
        entry("subentry").entries {
            entry("broken")
        }
    }
}

val entries = runBlocking {
    entry.flatten()
}

fun main(args: Array<String>) {

    println(entries)

    // this runs into a recursive typechacking error
    //val entries = entry.flatten()
    println(entries)

    val entriesList = runBlocking {
        entry.flatten()
    }
    println(entriesList)
}
```

It fails with the same
```
exception: java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: Back-end (JVM) Internal error: Failed to generate property entries
Cause: Error type encountered: [ERROR : Type for runBlocking {
    entry.flatten()
}] (DeferredType).
File being compiled at position: (67,1) in /Users/brandl/.kscript/kscript_tmp_project__kscript_166.kts_1536579114763/src/kscript_166_v2.kt
The root cause was thrown at: KotlinTypeMapper.java:113
File being compiled at position: file:///Users/brandl/.kscript/kscript_tmp_project__kscript_166.kts_1536579114763/src/kscript_166_v2.kt
The root cause was thrown at: MemberCodegen.java:218
	at org.jetbrains.kotlin.codegen.CompilationErrorHandler.lambda$static$0(CompilationErrorHandler.java:24)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:74)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:97)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:68)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:47)
```

So I'd suggest to report the issue to https://github.com/Kotlin/kotlinx.coroutines instead.
