### ISSUE TITLE
Confusing error when filename starts with a number -- Exception in thread "main" java.lang.ClassNotFoundException: ...

### ISSUE THREAD

**Issue by ivoanjo** [holgerbrandl/kscript#181]
Hello there, and thanks for kscript!

The other day I bumped onto this issue, and in retrospect it's a bit obvious, but it kind-of got me confused for a few minutes.

Because kscript tries to use the file name of the script as the kotlin class name to be compiled, this fails whenever the filename starts with a number, I'm assuming because that's not a valid Java class identifier name.

Example:

```bash
$ cat 1bug.kts 
println("Hello world")
```

Execution:

```kotlin
$ kscript 1bug.kts 
Exception in thread "main" java.lang.ClassNotFoundException: 1bug
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at Main_1bug$Companion.main(Main_1bug.kt:5)
        at Main_1bug.main(Main_1bug.kt)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
```

Could the invalid name be mapped into a simpler name and that one used as a class name? In my case I wanted to use a date as the first part of a file name (so that a bunch of simple scripts were naturally ordered by the date they were written), so it would be nice if this was supported.

**Comment by holgerbrandl** [comment]
Well spotted. The fix is still not a complete solution which would require to make sure that we covert the file name into a valid java identifier in the same way the kotlin script compiler is doing. Not sure about how to do so.

Still I think the fix should be good enough for now.

**Comment by ivoanjo** [comment]
👍👍👍 thanks for the quick fix!
