### ISSUE TITLE
Exception while loading classes from jars

### ISSUE THREAD

**Issue by rvprasad** [holgerbrandl/kscript#226]
When executed with `kscript t.kts` on 
 - Linux XYZ 4.14.34-hypriotos-v7+ #1 SMP Sun Apr 22 14:57:31 UTC 2018 armv7l GNU/Linux 
 - openjdk version "1.8.0_212" / OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-2~deb9u1-b03) / OpenJDK Client VM (build 25.212-b03, mixed mode)
 - Kotlin 1.3.31 
 - Kscript 2.7.1

the following code fails 
```
@file:CompilerOpts("-jvm-target 1.8")
@file:DependsOn("com.google.code.gson:gson:2.8.5")
@file:KotlinOpts("-J-Xmx1024M")

import com.google.gson.Gson
val gson = Gson()
println(gson.toJson(listOf(1, 2, 3)))
```
with the following error message
```
[kscript] Resolving dependencies...
[kscript]     Resolving com.google.code.gson:gson:2.8.5...Done
[kscript]     Resolving com.github.holgerbrandl:kscript-annotations:1.2...Done
[kscript] Dependencies resolved
[kscript] [ERROR] compilation of 't.kts' failed
Exception in thread "main" java.util.zip.ZipException: invalid entry size (expected 1839 but got 27434 bytes)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:384)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.jetbrains.kotlin.preloading.ClassPreloadingUtils.loadAllClassesFromJars(ClassPreloadingUtils.java:141)
	at org.jetbrains.kotlin.preloading.ClassPreloadingUtils.preloadClasses(ClassPreloadingUtils.java:49)
	at org.jetbrains.kotlin.preloading.Preloader.run(Preloader.java:61)
	at org.jetbrains.kotlin.preloading.Preloader.main(Preloader.java:43)
```
However, it runs successfully on  
 - Linux XYZ 5.0.0-15-generic #16pop0-Ubuntu SMP Wed May 15 14:41:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - openjdk version "1.8.0_212" / OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-linux64) (build 1.8.0_212-b04) / OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-linux64) (build 25.212-b04, mixed mode)
 - Kotlin 1.3.31 
 - Kscript 2.7.1

**Comment by rvprasad** [comment]
Uninstalling and reinstalling kotlin and kscript via sdkman fixed the issue; seems the installations were corrupt.  Sorry about the false alarm.
