### ISSUE TITLE
Remote execution of scripts with relative `@file:Include` statements fails

### ISSUE THREAD

**Issue by cgruber** [holgerbrandl/kscript#236]
Kscript doesn't interpret non-absolute URIs as being relative to a script when it's remotely executed, leading to exceptions like the following.

```
Exception in thread "main" java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088)
	at kscript.app.ResolveIncludesKt.resolveIncludes(ResolveIncludes.kt:39)
	at kscript.app.KscriptKt.main(Kscript.kt:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:110)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:120)
```

kscript should, ideally, take `@file:Include("foo.kt")` statements and, if executed from a script invoked via `kscript https://foo.bar/baz/blah.kts` and interpret the `foo.kt` reference as `https://foo.bar/baz/foo.kt`

Given that #219 improved relative referencing of `@file:Include` it seems that this doesn't take into account remote invocations.

**Comment by holgerbrandl** [comment]
Indeed that's a limitation of the current implementation. Feel welcome to contribute a PR to fix it. However, as stated before, imho the better model is to use gradle artefacts.

**Comment by cgruber** [comment]
Somewhat related, I'm finding even locally that's the case. if, in `bar.kts` I have `@File:Include("foo.kt")` it fails, if I am not calling it from the folder containing `foo.kt`

**Comment by aartiPl** [comment]
Same here. Not resolving included files relatively to script file makes structuring scripts really tricky. +1 for this feature from me.

**Comment by holgerbrandl** [comment]
Thanks for the feedback

**Comment by aartiPl** [comment]
This is now fixed in the 4.x version of kscript.
