### ISSUE TITLE
kscript invocation failure under MSYS2, but it works under Cygwin on the same machine.

### ISSUE THREAD

**Issue by vsajip** [holgerbrandl/kscript#368]
As per title. On MSYS2:
```
$ build/libs/kscript
Exception in thread "main" java.io.IOError: java.io.IOException: Unable to get working directory of drive 'H'
        at sun.nio.fs.WindowsPath.toAbsolutePath(WindowsPath.java:829)
        at sun.nio.fs.WindowsPath.toAbsolutePath(WindowsPath.java:44)
        at kscript.app.util.ShellUtils.guessKotlinHome(ShellUtils.kt:27)
        at kscript.app.model.ConfigBuilder.build(ConfigBuilder.kt:39)
        at kscript.app.KscriptKt.main(Kscript.kt:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:70)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:188)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:198)
Caused by: java.io.IOException: Unable to get working directory of drive 'H'
        ... 12 more

```

Whereas on Cygwin on the same machine:
```
$ build/libs/kscript
kscript - Enhanced scripting support for Kotlin on *nix-based systems.

Usage:
 kscript [options] <script> [<script_args>]...
 kscript --clear-cache

The <script> can be a script file (*kts), a script URL, - for stdin, a *.kt sour
ce file with a main method, or some kotlin code.

Use '--clear-cache' to wipe cached script jars and urls

Options:
 -i --interactive        Create interactive shell with dependencies as declared
in script
 -t --text               Enable stdin support API for more streamlined text proc
essing
 --idea                  Open script in temporary Intellij session
 -s --silent             Suppress status logging
 -d --development        Enable logging of exception stack trace and additional
log messages
 --package               Package script and dependencies into self-dependent bin
ary
 --add-bootstrap-header  Prepend bash header that installs kscript if necessary


Copyright : 2022 Holger Brandl
License   : MIT
Version   : v4.0.4
Website   : https://github.com/holgerbrandl/kscript
```

Repo version:
```
$ git rev-parse HEAD
dc827753adf707cf31cd220716e85139cae2d9cd
```

**Comment by vsajip** [comment]
Kotlin and OS/Bash versions:
```
$ kotlin -version
Kotlin version 1.6.21-release-334 (JRE 1.8.0_202-b08)

$ uname -a
CYGWIN_NT-10.0-19043 EPSILON-W10PRO 3.3.5-341.x86_64 2022-05-13 12:27 UTC x86_64 Cygwin

$ uname -a
MSYS_NT-10.0-19043 EPSILON-W10PRO 3.3.5-341.x86_64 2022-05-30 21:10 UTC x86_64 Msys
```

**Comment by aartiPl** [comment]
Seems to be fixed now on kscript_4.1 branch. Can you confirm?

**Comment by vsajip** [comment]
Yes, seems to work now. Thanks!
