### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by darkoverlordofdata** [holgerbrandl/kscript#6]
When I try the sample script, I get an error. But my script runs ok when I use:

kotlinc -script ./test.kts

Error:
Exception in thread "main" java.lang.UnsupportedClassVersionError: Main_Test : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:38)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:99)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:104)

**Comment by holgerbrandl** [comment]
This is a Java version mismatch. Could you use JRE/Java8 instead of the outdated Java7? This will fix the problem.

It seems that you're either
1) having a version difference between `javac` and `java` in your shell
2) or one of your declared dependencies was compiled with java8 and your using java7 in your shell.

Since kscript does not ship any compiled code, it's nothing I could actually fix.

If this does not help you to solve your problem, could you provide the test.kts, so that I can have a more in-depth look?

**Comment by darkoverlordofdata** [comment]
Hm, I'm on java version 1.8.0_91. There is another library that is working fine:
https://github.com/andrewoma/kotlin-script
I'l just use that,

**Comment by holgerbrandl** [comment]
Would you mind running
```
echo $JAVA_HOME
$JAVA_HOME/bin/javac -version
java -version
javac -version
```
 in your terminal and attaching the result to this ticket?

I could imagine a version mismatch in your setup since kotlinc is using JAVA_HOME to locate the compiler, but `kscript` was just running `java` from your PATH. If now the latter is v1.7 and the former pointing to an 1.8 installation, it would explain your problem.

The problem has been solved (see commit above) and simply reinstalling kscript with curl as indicated in the READM.md should fix it.
